services:
  db:
    image: postgres:16-alpine
    container_name: 69-s3-db
    ports:
      - 54327:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=prawee
      - POSTGRES_DB=prawee
  admin:
    image: dpage/pgadmin4
    container_name: 69-s3-admin
    ports:
      - 8083:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=prawee.w@fte.kmutnb.ac.th
      - PGADMIN_DEFAULT_PASSWORD=1p@ssw0rd